lib/kierroskone_web/router.ex
defmodule KierroskoneWeb.Router do
  use KierroskoneWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {KierroskoneWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])

    plug(KierroskoneWeb.CheckApiAuth)
  end

  scope "/", KierroskoneWeb do
    pipe_through(:browser)

    # Traditional artesanal server side rendered routes
    get("/", PageController, :index)
    get("/dead/tracks", PageController, :tracks)
    get("/dead/tracks/:id", PageController, :track)
    get("/dead/unclaimed", PageController, :unclaimed)
    get("/dead/claim/:id", PageController, :claim)
    post("/dead/claim/:id", PageController, :submit_claim)
    get("/dead/laptimes/:id", PageController, :laptime)
    get("/dead/laptimes/:id/telemetry", TelemetryController, :show)

    # Currently non-working (in prod) liveview stuff below this

    # GAMES
    live("/games", GameLive.Index, :index)
    live("/games/new", GameLive.Index, :new)
    live("/games/:id/edit", GameLive.Index, :edit)

    live("/games/:id", GameLive.Show, :show)
    live("/games/:id/show/edit", GameLive.Show, :edit)

    # TRACKS
    live "/tracks", TrackLive.Index, :index
    live "/tracks/new", TrackLive.Index, :new
    live "/tracks/:id/edit", TrackLive.Index, :edit

    live "/tracks/:id", TrackLive.Show, :show
    live "/tracks/:id/show/edit", TrackLive.Show, :edit

    # CLASSES
    live "/classes", ClassLive.Index, :index
    live "/classes/new", ClassLive.Index, :new
    live "/classes/:id/edit", ClassLive.Index, :edit

    live "/classes/:id", ClassLive.Show, :show
    live "/classes/:id/show/edit", ClassLive.Show, :edit

    # CARS
    live "/cars", CarLive.Index, :index
    live "/cars/new", CarLive.Index, :new
    live "/cars/:id/edit", CarLive.Index, :edit

    live "/cars/:id", CarLive.Show, :show
    live "/cars/:id/show/edit", CarLive.Show, :edit

    # USERS
    live "/users", UserLive.Index, :index
    live "/users/new", UserLive.Index, :new
    live "/users/:id/edit", UserLive.Index, :edit

    live "/users/:id", UserLive.Show, :show
    live "/users/:id/show/edit", UserLive.Show, :edit

    # LAPTIMES
    live "/laptimes", LaptimeLive.Index, :index
    live "/laptimes/new", LaptimeLive.Index, :new
    live "/laptimes/:id/edit", LaptimeLive.Index, :edit

    live "/laptimes/:id", LaptimeLive.Show, :show
    live "/laptimes/:id/show/edit", LaptimeLive.Show, :edit
  end

  scope "/api", KierroskoneWeb do
    pipe_through :api
    resources "/laptime-import/dirt2", Dirt2LaptimesUploadController, only: [:create]
    resources "/laptime-import/assettocorsa", AssettoCorsaLaptimesUploadController, only: [:create]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: KierroskoneWeb.Telemetry)
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end
end

lib/kierroskone_web/templates/page/claim.html.heex
<h1>Claim laptime for <%= @name %></h1>

<dl>
<dt>Track:</dt>
<dd><%= @laptime.track.name %></dd>
<dt>Car:</dt>
<dd><%= @laptime.car.name %></dd>
<dt>Class:</dt>
<dd><%= if is_nil(@laptime.car.class), do: "Unknown class", else: @laptime.car.class.name %></dd>
<dt>Time:</dt>
<dd><%= humanize_laptime(@laptime) %></dd>
<dt>Driven at:</dt>
<dd><%= @laptime.driven_at %></dd>
</dl>

<p><em>Claim this laptime for <%= @name %>?</em></p>

<%= button("Claim", to: Routes.page_path(@conn, :submit_claim, @laptime.id)) %>

lib/kierroskone_web/templates/page/index.html.heex
<section class="row">
  <article class="column">
    <h2>Things</h2>
    <ul>
      <li><%= link "Tracks", to: Routes.page_path(@conn, :tracks) %></li>
      <li><%= link "Unclaimed times", to: Routes.page_path(@conn, :unclaimed) %></li>
    </ul>
    <div style="display: none">
    <h2>Things that don't work</h2>
    <ul>
      <li>
        <%= link "Games", to: Routes.game_index_path(@conn, :index) %>
      </li>
      <li>
        <%= link "Classes", to: Routes.class_index_path(@conn, :index) %>
      </li>
      <li>
        <%= link "Cars", to: Routes.car_index_path(@conn, :index) %>
      </li>
      <li>
        <%= link "Tracks", to: Routes.track_index_path(@conn, :index) %>
      </li>
      <li>
        <%= link "Users", to: Routes.user_index_path(@conn, :index) %>
      </li>
      <li>
        <%= link "Laptimes", to: Routes.laptime_index_path(@conn, :index) %>
      </li>
    </ul>
    </div>
  </article>
</section>

lib/kierroskone_web/templates/page/laptime.html.heex
<h1>Laptime</h1>

<table>
  <tbody>
    <tr>
      <th>Track</th>
      <td><%= link(@laptime.track.name, to: Routes.page_path(@conn, :track, @laptime.track.id)) %></td>
    </tr>
    <tr>
      <th>Time</th>
      <td><%= humanize_laptime(@laptime) %></td>
    </tr>
    <tr>
      <th>Car</th>
      <td><%= @laptime.car.name %><%= if !is_nil(@laptime.car.class), do: " (#{@laptime.car.class.name})" %></td>
    </tr>
    <tr>
      <th>Driver</th>
      <td><%= if is_nil(@laptime.user), do: link("Claim", to: Routes.page_path(@conn, :claim, @laptime.id)), else: @laptime.user.name %></td>
    </tr>
    <tr>
      <th>Recorded at</th>
      <td><%= @laptime.driven_at %></td>
    </tr>
  </tbody>
</table>

<h2>Visualisation</h2>
<div id="telemetry-visualisation" style="height: 500px" data-laptime-id={@laptime.id} data-record-id={@record.id}></div>

lib/kierroskone_web/templates/page/track.html.heex
<h1><%= @track.name %><%= if not is_nil(@track.game), do: " (#{@track.game.name})"%></h1>

<h2>Overall lap record:</h2>
<%=
cond do
  is_nil(@record) ->
    "Not available"
  true ->
    "#{humanize_laptime(@record)} by #{@record.user.name} on #{@record.inserted_at} in a #{@record.car.name}"
end
%>

<h2>Fastest times per car:</h2>
<ul>
  <%= for record <- @records do %>
  <li><%= record.car.name %><%= if not is_nil(record.car.class), do: " (#{record.car.class.name})" %>: <%= humanize_laptime(record) %><%= if !is_nil(record.user), do: " by #{record.user.name}" %> on <%= record.inserted_at %></li>
  <% end %>
</ul>

<h2>Laptimes:</h2>
<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Car</th>
      <th>Driver</th>
      <th>Recorded at</th>
    </tr>
  </thead>
  <tbody>
    <%= for laptime <- @laptimes do %>
      <tr>
        <td><%= link(humanize_laptime(laptime), to: Routes.page_path(@conn, :laptime, laptime.id)) %></td>
        <td><%= laptime.car.name %><%= if !is_nil(laptime.car.class), do: " (#{laptime.car.class.name})" %></td>
        <td><%= if is_nil(laptime.user), do: link("Claim", to: Routes.page_path(@conn, :claim, laptime.id)), else: laptime.user.name %></td>
        <td><%= laptime.driven_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/kierroskone_web/templates/page/tracks.html.heex
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Game</th>
      <th>Overall lap record</th>
      <th>Record holder</th>
    </tr>
  </thead>
  <tbody id="tracks">
    <%= for {track, record} <- @tracks do %>
      <tr id={"track-#{track.id}"}>
        <td><%= link track.name, to: Routes.page_path(@conn, :track, track.id) %></td>
        <td>
          <span><%= if is_nil(track.game), do: "Not set", else: track.game.name %></span>
        </td>
        <%= if is_nil(record) do %>
          <td colspan="2">Not available</td>
        <% else %>
          <td><%= humanize_laptime(record) %></td>
          <td><%= record.user.name %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

lib/kierroskone_web/templates/page/unclaimed.html.heex
<h1>Unclaimed laptimes for the past week</h1>

<table>
<thead>
<tr>
	<th>Track</th>
	<th>Car</th>
	<th>Time</th>
	<th>Recorded at</th>
	<th></th>
</tr>
</thead>
<tbody>
<%= for laptime <- @laptimes do %>
	<tr>
		<td><%= laptime.track.name %></td>
		<td><%= laptime.car.name %><%= if !is_nil(laptime.car.class), do: " (#{laptime.car.class.name})" %></td>
		<td><%= humanize_laptime(laptime) %></td>
		<td><%= laptime.driven_at %></td>
		<td><%= link("Claim", to: Routes.page_path(@conn, :claim, laptime.id)) %></td>
	</tr>
<% end %>
</tbody>
</table>